### PR TITLE
Bump to version 5.3.3

### PR DESCRIPTION
**Pull request by jakirkham**
Bumps `master` to the latest version. Not sure if these patches are still required.

### CODE REVIEW

**Comment by jakirkham** [comment]
Had to update the `luaconf.patch` to get it to work as things had moved around and changed a bit. Maybe it is worth submitting these patches to upstream so we don't have to maintain them separately here.

**Comment by jakirkham** [comment]
This is for `5.3.3`, but it looks like `5.3.4` is right around the corner. Probably can still merge this and then continue on to `5.3.4`.

xref: https://github.com/lua/lua/commit/08199ade4ace6addd63148df4c596d6b61def8cd

**Comment by jakirkham** [comment]
Please let me know if anything else is required @alexbw .

**Comment by alexbw** [comment]
FYI, I'm no longer actively using these repos, so if you know of a better maintainer, or you just want to merge things automatically without me, please do.

**Comment by jakirkham** [comment]
Thanks for letting us know. I think we may merge some things ourselves in the near term and then determine what we want to do for the long term later.

**Pull request merged**
