### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/lua-feedstock/pull/8

Added for the `master` branch.

cc @jjhelmus

### CODE REVIEW

**Comment by jakirkham** [comment]
Might be worthwhile to merge PR ( https://github.com/conda-forge/lua-feedstock/pull/16 ) first.

**Comment by jakirkham** [comment]
Might be worthwhile to merge PR ( https://github.com/conda-forge/lua-feedstock/pull/16 ) to get the new release first.

**Comment by jakirkham** [comment]
Could you please take a look at this, @jjhelmus ?

**Comment by jakirkham** [comment]
As per our discussion in the meeting, I'm going to go ahead and merge this.

**Comment by jjhelmus** [comment]
Thanks for keeping on top of these @jakirkham.  Sorry for the long delay.  Work and the holidays had me quite busy the last two weeks.

**Pull request merged**
